### ISSUE TITLE
如何选择ibopencv_java.so

### ISSUE THREAD

**Issue by freedomofme** [weixsong/libra#1]
博主，你好，在你的GitHub上看到（https://github.com/weixsong/libra#asmdemo）我发现了这样一段： in order to make this project runable, you need to select correct libopencv_java.so according to your hardware platform, default target ABI is amerabi, if you are using other hardware platform, checkout what platform you are using and select libopencv_java.so from corresponding platform library that Opencv4Android has already built for you.
反复读了几遍后，我明白需要根据运行的机器的CPU构架选择对应的文件ibopencv_java.so，然后复制到jni目录下。
 同时在我的Opencv4Android文件中的armeabi和aremeabi-v7和x86下都有这个libopencv_java.so文件。
我希望项目的APP是适配所有构架的，请问该如何做？是把所有不同构架的libopencv_java.so都复制到jni目录下（那么需要如何存放）还是一次只能复制一个ibopencv_java.so（此种方法就不能一个APP兼容所有构架）？

**Comment by weixsong** [comment]
Hi, @freedomofme , 你提出的问题确实是个应该解决的问题。
我记得opencv有一个OpenCvManager类似的控制系统，可以针对用户的硬件架构自动的选择对应的动态链接库文件。
你看一下Opencv4Android的Examples里面，应该有类似于OpencvManager的应用。

**Comment by freedomofme** [comment]
好的，谢谢，我刚刚粗略看了下OpenCV4Android的sample目录，貌似没找到你说的。
不过我会继续学习Opencv4Android方面的内容，继续追寻这个问题。有想法了再交流~

Best Regards

原始邮件
发件人:wei songnotifications@github.com
收件人:weixsong/libralibra@noreply.github.com
抄送:Huangxiegeixiong@gmail.com
发送时间:2015年11月9日(周一) 09:23
主题:Re: [libra] 如何选择ibopencv_java.so (#1)

Hi, @freedomofme , 你提出的问题确实是个应该解决的问题。
 我记得opencv有一个OpenCvManager类似的控制系统，可以针对用户的硬件架构自动的选择对应的动态链接库文件。
 你看一下Opencv4Android的Examples里面，应该有类似于OpencvManager的应用。

**Comment by weixsong** [comment]
Hi, @freedomofme , I think the following link would be help:
https://docs.google.com/presentation/d/1EO_1kijgBg_BsjNp2ymk-aarg-0K279_1VZRcPplSuk/present?slide=id.p
http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/O4A_SDK.html#running-opencv-samples
http://docs.opencv.org/2.4/platforms/android/service/doc/UseCases.html#manager-selection

There is an issue with Opencv Manager: if you want to use Opencv Manager, you need to be able to connect Google Play Market, but actually in China you can't.

Good luck!

**Comment by freedomofme** [comment]
Thank you very much with your help.
As a developer, you konw that...
I will see the article of web links blow as soon as possible.

Best Regards

原始邮件
发件人:wei songnotifications@github.com
收件人:weixsong/libralibra@noreply.github.com
抄送:Huangxiegeixiong@gmail.com
发送时间:2015年11月10日(周二) 15:44
主题:Re: [libra] 如何选择ibopencv_java.so (#1)

Hi, @freedomofme , I think the following link would be help:
 https://docs.google.com/presentation/d/1EO_1kijgBg_BsjNp2ymk-aarg-0K279_1VZRcPplSuk/present?slide=id.p
 http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/O4A_SDK.html#running-opencv-samples
 http://docs.opencv.org/2.4/platforms/android/service/doc/UseCases.html#manager-selection
There is an issue with Opencv Manager: if you want to use Opencv Manager, you need to be able to connect Google Play Market, but actually in China you can't.
Good luck!
